### ISSUE TITLE
In the quickstart the integration between KSQL, SR en the brokers is not working

### ISSUE THREAD

**Issue by bartgel** [confluentinc/confluent-kubernetes-examples#156]
In the quickstar, in order to better showcase the integration of the components:

**For the brokers**
The kafka-brokers needs the following configuration under spec

```
  configOverrides:
    server:
    - confluent.schema.registry.url=http://schemaregistry.confluent.svc.cluster.local:8081  
```

This will allow you to be able to set the confluent_value_validation on a topic

**For KsqlDb**
KsqlDb needs to integrate with the broker and connect with schema registry:

```
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
  configOverrides:
    server:
    - ksql.schema.registry.url=http://schemaregistry.confluent.svc.cluster.local:8081  
```
