### ISSUE TITLE
Is confluent-rolebinding supported for Confluent Cloud?

### ISSUE THREAD

**Issue by vSivarajah** [confluentinc/confluent-kubernetes-examples#207]
Resources such as Topics and schemas can be provisioned using the CustomResources: KafkaTopics and Schemas. However i am failing to provision Rolebindings for Confluent Cloud:

```
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: kafka-rb
spec:
  principal:
    type: user
    name: u-test
  clustersScopeByIds:
    kafkaClusterId: lkc-0test
  kafkaRestClassRef:
    name: default
    namespace: confluent
  resourcePatterns:
  - name: "*"
    patternType: PREFIXED
    resourceType: Topic
  role: DeveloperRead
```

```
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: default
  namespace: confluent
spec:
  kafkaRest: 
    endpoint: https://api.confluent.cloud/iam/v2
    kafkaClusterID: lkc-0test
    authentication:
      bearer:
        secretRef: rest-creds
      type: bearer
```

In the controller logs: 

```
"controllers/confluentrolebinding_controller.go:130","msg":"apply failed","name":"kafka","namespace":"confluent","error":"kafka rest API request failed: Not Found (0)"
```

Has anyone actually tried to create a rolebinding that gets provisioned in confluent cloud? What am i missing in the configuration?
