### ISSUE TITLE
Control Center with basic auth kafka connect dependency

### ISSUE THREAD

**Issue by aidan-melen** [confluentinc/confluent-kubernetes-examples#212]
This configuration doesn't work:

```yaml
---
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: confluent
spec:
  replicas: 1
  authentication:
    type: basic
    basic:
      secretRef: basicsecret
  tls:
    autoGeneratedCerts: true
  image:
    application: confluentinc/cp-server-connect:7.3.0
    init: confluentinc/confluent-init-container:2.5.0
  dependencies:
    kafka:
      bootstrapEndpoint: kafka:9071

---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center:7.3.0
    init: confluentinc/confluent-init-container:2.5.0
  dataVolumeCapacity: 10Gi
  dependencies:
   connect:
      url: https://connect.confluent.svc.cluster.local:8083
      authentication:
        type: basic
        basic:
          secretRef: basicsecret
```

I am seeing the following `WARN` logs:

```
[2023-02-07 21:05:32,689] WARN [armeria-common-worker-epoll-2-2] [creqId=xxxxxxxx, chanId=xxxxxxxx, laddr=10.133.151.141:53104, │
│  raddr=connect/x.x.x.x:8083][https://connect:8083/v1/metadata/id#GET] Unexpected 4xx health check respo │
│ nse: [:status=401, date=Tue, 07 Feb 2023 21:05:32 GMT, content-type=application/json, content-length=32] A 4xx response generally indicates a mis │
│ configuration of the client. Did you happen to forget to configure the HealthCheckedEndpointGroup's client options? (com.linecorp.armeria.client. │
│ endpoint.healthcheck.HttpHealthChecker)
```

I thought I would find the answer in the examples; however, the [plaintext-basic-auth-Connect](https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/security/plaintext-basic-auth-Connect) example configures connect with basic auth but conveniently does not add specify connect as a dependency. Is this an unsupported configuration?

I know the Kafka Connect basic auth rest endpoint is valid and know Control Center can talk to Connect over unauthenticated/TLS.

```bash
# using an self-signed autogenerated cert
$ curl --insecure -u connect:xxxxxxxxxxxxxxxx https://connect:8083/v1/metadata/id#GET | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   113  100   113    0     0   3424      0 --:--:-- --:--:-- --:--:--  3424
{
  "id": "",
  "scope": {
    "path": [],
    "clusters": {
      "kafka-cluster": "XXXXXXXXXXXXXXXX",
      "connect-cluster": "connect"
    }
  }
}
```
