### ISSUE TITLE
Configure kafkaRest with tls.enabled=true and secretRef in examples

### ISSUE THREAD

**Issue by pkleindl** [confluentinc/confluent-kubernetes-examples#318]
Enabling TLS on the kafkaRest dependency requires the secretRef to be set there, too, even if the same secretRef is set at the higher level on spec.tls.secretRef.

This resulted in the ERROR "tls client secretRef or directoryPathInContainer must be set in spec" in the operators logs and caused all changes after startup not to be applied to the cluster.

```
dependencies:
  kafkaRest:
     authentication:
        bearer:
          secretRef: kafka-credential
        type: bearer
      tls:
        enabled: true
        secretref: here
```

For details, see https://support.confluent.io/hc/en-us/requests/234433 (not public)
Copied from the issue:
<img width="774" alt="image" src="https://github.com/user-attachments/assets/71d66db8-7165-4e05-b7f4-dd0df3913db9">
