### ISSUE TITLE
RecordTooLargeException with max.request.size override

### ISSUE THREAD

**Issue by santurini** [confluentinc/confluent-kubernetes-examples#355]
I have deployed a standalone KafkaConnect cluster with this manifest:
```yaml
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-zookeeper:7.9.0
    init: confluentinc/confluent-init-container:2.11.0
  dataVolumeCapacity: 10Gi
  logVolumeCapacity: 10Gi
  configOverrides:
    server:
      - auto.create.topics.enable=true
      - log.retention.hours=3
      - log.roll.hours=3
      - log.cleaner.delete.retention.ms=10800000
      - confluent.offsets.log.cleaner.delete.retention.ms=10800000
      - message.max.bytes=67108864
      - max.request.size=67108864

---

apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-server:7.9.0
    init: confluentinc/confluent-init-container:2.11.0
  dataVolumeCapacity: 750Gi
  configOverrides:
    jvm:
      - -Xmx32G
      - -Xms1G
      - -XX:MaxRAMPercentage=90.0
    server:
      - auto.create.topics.enable=true
      - log.retention.hours=3
      - log.roll.hours=3
      - log.cleaner.delete.retention.ms=10800000
      - confluent.offsets.log.cleaner.delete.retention.ms=10800000
      - confluent.license.topic.replication.factor=1
      - confluent.metrics.reporter.topic.replicas=1
      - confluent.tier.metadata.replication.factor=1
      - confluent.metadata.topic.replication.factor=1
      - confluent.balancer.topic.replication.factor=1
      - confluent.security.event.logger.exporter.kafka.topic.replicas=1
      - event.logger.exporter.kafka.topic.replicas=1
      - offsets.topic.replication.factor=1
      - confluent.cluster.link.enable=true
      - message.max.bytes=67108864
      - max.request.size=67108864

---

apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-server-connect:7.9.0
    init: confluentinc/confluent-init-container:2.11.0
  configOverrides:
    jvm:
      - -Xmx96G
      - -Xms1G
      - -XX:MaxRAMPercentage=90.0
    server:
      - config.storage.replication.factor=1
      - offset.storage.replication.factor=1
      - status.storage.replication.factor=1
      - message.max.bytes=67108864
      - max.request.size=67108864
  podTemplate:
    envVars:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-credentials
            key: aws_access_key_id
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-credentials
            key: aws_secret_access_key
      - name: AWS_REGION
        value: eu-central-1
  build:
    type: onDemand
    onDemand:
      plugins:
        confluentHub:
          - name: debezium-connector-mysql
            owner: debezium
            version: latest
          - name: iceberg-kafka-connect
            owner: tabular
            version: latest

---

apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center:7.9.0
    init: confluentinc/confluent-init-container:2.11.0
  dataVolumeCapacity: 10Gi
  configOverrides:
    server:
      - confluent.controlcenter.command.topic.replication=1
      - confluent.controlcenter.replication.factor=1
      - confluent.metrics.reporter.topic.replicas=1
      - confluent.metrics.topic.replication=1
      - confluent.monitoring.interceptor.topic.replication=1
      - confluent.controlcenter.internal.topics.replication=1
  dependencies:
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
    connect:
    - name: connect-dev
      url:  http://connect.confluent.svc.cluster.local:8083

---

apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-schema-registry:7.9.0
    init: confluentinc/confluent-init-container:2.11.0

---

apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: control.iceberg
  namespace: confluent
  annotations:
    platform.confluent.io/wait-for: "kafka.confluent"
spec:
  kafkaClusterRef:
    name: kafka
    namespace: confluent
  replicas: 1
  partitionCount: 1
```

And then I deploy a debezium connector to ingest data from MySQL but for a particular table the connector fails to do the snapshot with this error, even if I've set both `max.request.size` and `message.max.bytes`:
```java
Caused by: org.apache.kafka.common.errors.RecordTooLargeException: The message is 1618815 bytes when serialized which is larger than 1048576, which is the value of the max.request.size configuration.
```
