### ISSUE TITLE
Configure locationType: url correctly for kubernetes

### ISSUE THREAD

**Issue by MaxPrimeAERY** [confluentinc/confluent-kubernetes-examples#98]
Hello!
I am trying to configure kafka connect for kubernetes.
In docs I've found how to add locationType: confluenthub and url.
Confluenthub config works great but I am trying also to use url from maven repository. How can I do that correctly ?

```
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-server-connect:7.0.1
    init: confluentinc/confluent-init-container:2.2.0-1
  configOverrides:
    server:
      - config.storage.replication.factor=1
      - offset.storage.replication.factor=1
      - status.storage.replication.factor=1
 build:
    type: onDemand
    onDemand:
      plugins:
        locationType: confluentHub #works great
        confluentHub:
          - name: kafka-connect-jdbc
            owner: confluentinc
            version: 10.2.6
          - name: kafka-connect-oracle-cdc
            owner: confluentinc
            version: 1.5.0
          - name: debezium-connector-mysql
            owner: debezium
            version: 1.7.1
          - name: debezium-connector-postgresql
            owner: debezium
            version: 1.7.1
      storageLimit: 4Gi
  podTemplate:
    resources:
      requests:
        cpu: 200m
        memory: 1024Mi
    probe:
      liveness:
        periodSeconds: 180 #DONT CHANGE THIS
        failureThreshold: 5
        timeoutSeconds: 500
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
```
What I did try.

```
locationType: url #NOT WORKING. NO IDEA HOW TO CONFIGURE THAT
    url:
       - name: mysql-connector-java
         archivePath: https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.26/mysql-connector-java-8.0.26.jar
         checksum: sha512sum    #definitely wrong
```
Also I tried making docker image but it doesn't work. (Pod is Unready all the time).

**Comment by MosheBlumbergX** [comment]
Hi @MaxPrimeAERY , here is an example of how this should look like: 

https://github.com/confluentinc/confluent-kubernetes-examples/blob/master/hybrid/ccloud-JDBC-mysql/kafka-connect.yaml#L13-L21

```
  build:
    type: onDemand
    onDemand:
      plugins:
        locationType: url
        url:
          - name: kafka-connect-jdbc 
            archivePath: https://raw.githubusercontent.com/confluentinc/confluent-kubernetes-examples/master/hybrid/ccloud-JDBC-mysql/confluentinc-kafka-connect-jdbc-10.2.5.zip
            checksum: 9d033fabac89ec0b35a97246f7ca3a36800bcb402ccfbd76adebd4c4c9ca6e7d6a044a9162383a18f99400893581b55a87b9fe89e35276507e9a3fb6cff3fda0
  
```
